#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef MAPZONESPEEDALERTSDK_SWIFT_H
#define MAPZONESPEEDALERTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MapZoneSpeedAlertSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class CLLocation;
@class NSString;
SWIFT_CLASS("_TtC20MapZoneSpeedAlertSDK23EnhancedLocationManager")
@interface EnhancedLocationManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(CLLocation * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onLocationError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onAuthorizationChanged)(CLAuthorizationStatus);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)stopTracking;
- (void)requestLocationPermissions SWIFT_AVAILABILITY(ios,introduced=14.0);
- (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
- (CLLocation * _Nullable)getLastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocationServicesStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullAccuracy;
- (void)setCustomAccuracy:(CLLocationAccuracy)accuracy distanceFilter:(CLLocationDistance)distanceFilter;
- (void)enableBackgroundLocationUpdates:(BOOL)enable SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

@class CLLocationManager;
@interface EnhancedLocationManager (SWIFT_EXTENSION(MapZoneSpeedAlertSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManagerDidChangeAuthorization:(CLLocationManager * _Nonnull)manager SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

/// Entry point for the MapZone Speed Alert engine on iOS.
/// Holds the configuration for a single vehicle profile and forwards each
/// GPS update to the native engine. The engine performs zone loading,
/// map-matching, speed-sign bitmap rendering, and voice clip generation
/// on background queues; this class only schedules work and dispatches
/// results back to the main thread.
/// <h3>Usage</h3>
/// \code
/// // 1. Create with vehicle credentials and profile.
/// let manager = ZoneNetworkManager(
///     baseUrl: "https://driving.map.zone",
///     apiKeyId: "<apiKeyId>", apiKey: "<apiKey>",
///     bundleId: Bundle.main.bundleIdentifier ?? "",
///     vehicleId: "<vehicleId>",
///     vehicleType: 1, seats: 1, weights: 1)
///
/// // 2. Subscribe to UI events.
/// manager.onReady   = { links, alerts in ... }
/// manager.onBitmap  = { current, status, next, nextDist,
///                       camera, camDist, toll, tollDist, voiceWav in ... }
/// manager.onResult = { success, code, message in ... }
///
/// // 3. Feed every GPS frame.
/// manager.updateLocation(lat: lat, lng: lng,
///                        speedKmh: speedKmh, bearingDeg: bearing)
/// manager.processGps(lat: lat, lng: lng, bearing: bearing,
///                    speedKmh: speedKmh, accuracy: accuracy)
///
/// \endcodeAll public methods are safe to call from the main thread. Internally
/// the manager uses a single serial dispatch queue so calls are
/// serialised — concurrent <code>updateLocation</code> and <code>processGps</code> will not
/// race against each other.
SWIFT_CLASS("_TtC20MapZoneSpeedAlertSDK18ZoneNetworkManager")
@interface ZoneNetworkManager : NSObject
/// Fired on the main thread after each successful zone load.
/// Use it to enable UI that depends on having data — e.g. show the
/// speed-sign panel, or refresh a debug overlay with the new zone
/// bbox. Parameters are <code>(linkCount, alertCount)</code>.
@property (nonatomic, copy) void (^ _Nullable onReady)(NSInteger, NSInteger);
/// Fired on the main thread after every zone-reload attempt.
/// Useful for surfacing server-side errors to the user.
/// <ul>
///   <li>
///     <code>success</code>: <code>true</code> when fresh zone data was loaded.
///   </li>
///   <li>
///     <code>errorCode</code>: <code>0</code> on success. Positive values are server-reported
///     errors (e.g. <code>2003</code> unauthorized, <code>1001</code> invalid parameter,
///     <code>3003</code> vehicle type not supported). Negative values are local
///     SDK failures (network, parse).
///   </li>
///   <li>
///     <code>errorMessage</code>: human-readable detail, may be empty on success.
///   </li>
/// </ul>
@property (nonatomic, copy) void (^ _Nullable onResult)(BOOL, NSInteger, NSString * _Nonnull);
/// Create a manager for the authenticated profile.
/// note:
/// Throws an Objective-C exception with name
/// <code>"InvalidArgument"</code> if <code>baseUrl</code> does not start with <code>https://</code>.
/// \param baseUrl Bare host of the zone API, e.g.
/// <code>"https://driving.map.zone"</code>. Must start with <code>https://</code>.
///
/// \param apiKeyId Public API Key ID issued for this app.
///
/// \param apiKey Authentication secret paired with <code>apiKeyId</code>. Treat
/// it as a credential: do not log it, embed it in source
/// control, or expose it in user-facing UI.
///
/// \param bundleId Application bundle ID whitelisted for this key,
/// typically <code>Bundle.main.bundleIdentifier</code>.
///
/// \param vehicleId Vehicle identifier associated with <code>apiKeyId</code>.
///
/// \param vehicleType Vehicle category code (see SDK integration guide).
///
/// \param seats Number of seats — used to filter applicable alerts.
///
/// \param weights Vehicle gross weight in kg — used to filter applicable alerts.
///
- (nonnull instancetype)initWithBaseUrl:(NSString * _Nonnull)baseUrl apiKeyId:(NSString * _Nonnull)apiKeyId apiKey:(NSString * _Nonnull)apiKey bundleId:(NSString * _Nonnull)bundleId vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(NSInteger)weights OBJC_DESIGNATED_INITIALIZER;
/// Notify the engine of a position change without motion context.
/// Equivalent to <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code> with
/// <code>speedKmh = 0</code> and <code>bearingDeg = .nan</code>. Most integrations should
/// prefer the four-argument overload so the engine can prefetch the
/// next zone earlier when driving fast and along the heading.
- (void)updateLocationWithLat:(double)lat lng:(double)lng;
/// Notify the engine of a position change with motion context.
/// Safe to call on the main thread — the actual zone work runs on a
/// background queue. Call this on every GPS update. The engine
/// internally throttles network requests, so calling at 1 Hz costs
/// nothing when the vehicle hasn’t moved far enough to warrant a
/// reload.
/// \param lat Latitude in degrees (WGS84).
///
/// \param lng Longitude in degrees (WGS84).
///
/// \param speedKmh Current GPS speed in km/h. Forwarded to the engine
/// so the prefetch margin scales with speed: faster driving
/// triggers the next zone fetch further ahead of the edge.
///
/// \param bearingDeg Heading in degrees (0 = N, 90 = E). The request
/// sent to the server is projected ~400m forward along this
/// bearing so an edge-of-zone GPS does not produce a
/// same-zone response. Pass <code>.nan</code> when bearing is unknown.
///
- (void)updateLocationWithLat:(double)lat lng:(double)lng speedKmh:(double)speedKmh bearingDeg:(double)bearingDeg;
/// Feed a GPS frame to the matching and alert pipeline.
/// This drives the per-tick UI: map-matching, current speed-sign
/// lookup, “next sign / camera / toll” preview, speeding detection,
/// and voice cue generation. Call once per GPS update, after
/// <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code>.
/// Runs on the same serial queue as <code>updateLocation</code>, so the engine
/// never sees a <code>processGps</code> call mid-way through a zone reload.
/// \param lat Latitude in degrees (WGS84).
///
/// \param lng Longitude in degrees (WGS84).
///
/// \param bearing Heading in degrees (0 = N, 90 = E).
///
/// \param speedKmh Current speed in km/h.
///
/// \param accuracy Horizontal accuracy radius in metres
/// (<code>CLLocation.horizontalAccuracy</code>).
///
- (void)processGpsWithLat:(double)lat lng:(double)lng bearing:(double)bearing speedKmh:(double)speedKmh accuracy:(double)accuracy;
/// Clear all loaded zone data and reset internal state.
/// Call this when the vehicle profile changes (e.g. driver swaps
/// <code>vehicleType</code> / <code>seats</code> / <code>weights</code>) or when the user ends a
/// navigation session and you want to free the engine’s memory. The
/// next <code>updateLocation</code> call will trigger a fresh fetch.
- (void)reset;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
