#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef MAPZONESPEEDALERTSDK_SWIFT_H
#define MAPZONESPEEDALERTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MapZoneSpeedAlertSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class CLLocation;
@class NSString;
SWIFT_CLASS("_TtC20MapZoneSpeedAlertSDK23EnhancedLocationManager")
@interface EnhancedLocationManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(CLLocation * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onLocationError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onAuthorizationChanged)(CLAuthorizationStatus);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)stopTracking;
- (void)requestLocationPermissions SWIFT_AVAILABILITY(ios,introduced=14.0);
- (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
- (CLLocation * _Nullable)getLastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocationServicesStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullAccuracy;
- (void)setCustomAccuracy:(CLLocationAccuracy)accuracy distanceFilter:(CLLocationDistance)distanceFilter;
- (void)enableBackgroundLocationUpdates:(BOOL)enable SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

@class CLLocationManager;
@interface EnhancedLocationManager (SWIFT_EXTENSION(MapZoneSpeedAlertSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManagerDidChangeAuthorization:(CLLocationManager * _Nonnull)manager SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

/// Vehicle type for MapZone Speed Alert SDK.
/// Values aligned with Zone Network v4 backend enum
/// (<code>drivingalert/api/v1/Zone/network?vehicleType=...</code>).
typedef SWIFT_ENUM(NSInteger, VehicleType, open) {
  VehicleTypeCar = 1,
  VehicleTypeMotorcycle = 2,
  VehicleTypeTruck = 3,
  VehicleTypeCoach = 4,
  VehicleTypeBus = 5,
  VehicleTypeTaxi = 6,
  VehicleTypeBicycle = 7,
  VehicleTypePedestrian = 8,
  VehicleTypeEmergency = 9,
};

/// Configurable voice-alert categories the host app can mute.
/// Each case maps 1:1 to a native <code>VoiceTrigger</code> (see <code>graph_engine_v2.hpp</code>).
/// Use with <code>ZoneNetworkManager/setMutedAlertTypes(_:)</code> to choose which
/// alert voices are spoken and which are skipped. From Objective-C, call
/// <code>ZoneNetworkManager/setMutedAlertTypeValues(_:)</code> instead and box these
/// values in <code>NSNumber</code> — a <code>Set</code> of enums cannot cross the ObjC bridge.
/// note:
/// Speed-limit (“hiện tại” / “tiếp theo”) and speeding warnings are
/// core safety cues and are always announced — they have no case here, and
/// their on-screen sign always shows.
/// Muting a camera or toll category also hides its on-screen icon together
/// with its voice. The other sign categories (no-turn, no-parking, …)
/// currently have no icon, so muting them only silences the voice.
typedef SWIFT_ENUM(NSInteger, VoiceAlertType, open) {
  VoiceAlertTypeSpeedCamera = 3,
  VoiceAlertTypeToll = 4,
  VoiceAlertTypeTrafficEnforcementCamera = 6,
  VoiceAlertTypeRedLightCamera = 7,
  VoiceAlertTypeAiCamera = 8,
  VoiceAlertTypeNoLeftTurn = 9,
  VoiceAlertTypeNoRightTurn = 10,
  VoiceAlertTypeNoUTurn = 11,
  VoiceAlertTypeNoOvertaking = 12,
  VoiceAlertTypeNoOvertakingEnd = 13,
  VoiceAlertTypeNoParking = 14,
  VoiceAlertTypeNoStraight = 15,
  VoiceAlertTypeBuildUpAreaStart = 16,
  VoiceAlertTypeBuildUpAreaEnd = 17,
  VoiceAlertTypeRestStation = 18,
  VoiceAlertTypeNoStopping = 19,
  VoiceAlertTypeRoadClosed = 20,
  VoiceAlertTypeVehicleRestricted = 21,
};

@class UIImage;
@class NSData;
@class NSNumber;
/// Entry point for the MapZone Speed Alert engine on iOS.
/// Holds the configuration for a single vehicle profile and forwards each
/// GPS update to the native engine. The engine performs zone loading,
/// map-matching, speed-sign bitmap rendering, and voice clip generation
/// on background queues; this class only schedules work and dispatches
/// results back to the main thread.
/// <h3>Usage</h3>
/// \code
/// // 1. Create, then configure with vehicle credentials and profile.
/// let manager = ZoneNetworkManager()
/// manager.configure(
///     baseUrl: "https://driving.map.zone",
///     apiKeyId: "<apiKeyId>", apiKey: "<apiKey>",
///     vehicleId: "<vehicleId>",
///     vehicleType: 1, seats: 1, weights: 1)
///
/// // 2. Subscribe to UI events.
/// manager.onReady   = { links, alerts in ... }
/// manager.onBitmap  = { current, status, next, nextDist,
///                       camera, camDist, toll, tollDist, voiceWav in ... }
/// manager.onResult = { success, code, message in ... }
/// manager.onAccessRestriction = { bmp, kind, distMeters in ... }
/// manager.onStopRestriction   = { bmp, kind, distMeters in ... }
/// manager.onBuildupArea       = { bmp, kind, distMeters in ... }
///
/// // 3. Feed every GPS frame.
/// manager.updateLocation(lat: lat, lng: lng,
///                        speedKmh: speedKmh, bearingDeg: bearing)
/// manager.processGps(lat: lat, lng: lng, bearing: bearing,
///                    speedKmh: speedKmh, accuracy: accuracy,
///                    timestampMs: Int64(location.timestamp
///                                         .timeIntervalSince1970 * 1000))
///
/// \endcodeAll public methods are safe to call from the main thread. Internally
/// the manager uses a single serial dispatch queue so calls are
/// serialised — concurrent <code>updateLocation</code> and <code>processGps</code> will not
/// race against each other.
SWIFT_CLASS("_TtC20MapZoneSpeedAlertSDK18ZoneNetworkManager")
@interface ZoneNetworkManager : NSObject
/// Fired on the main thread after each successful zone load.
/// Use it to enable UI that depends on having data — e.g. show the
/// speed-sign panel, or refresh a debug overlay with the new zone
/// bbox. Parameters are <code>(linkCount, alertCount)</code>.
@property (nonatomic, copy) void (^ _Nullable onReady)(NSInteger, NSInteger);
/// Fired on the main thread after every zone-reload attempt.
/// Useful for surfacing server-side errors to the user.
/// <ul>
///   <li>
///     <code>success</code>: <code>true</code> when fresh zone data was loaded.
///   </li>
///   <li>
///     <code>errorCode</code>: <code>0</code> on success. Positive values are server-reported
///     errors (e.g. <code>2003</code> unauthorized, <code>1001</code> invalid parameter,
///     <code>3003</code> vehicle type not supported). Negative values are local SDK
///     failures: <code>-1</code> response could not be verified, <code>-2</code> data invalid,
///     <code>-3</code> secure session failed, <code>-4</code> server unreachable, <code>-5</code> the
///     native bridge failed (rejected configuration, call threw).
///   </li>
///   <li>
///     <code>errorMessage</code>: a curated sentence derived from <code>errorCode</code> alone.
///     The server’s own wording never appears here — localise off the
///     numeric code if you need anything other than English.
///   </li>
/// </ul>
@property (nonatomic, copy) void (^ _Nullable onResult)(BOOL, NSInteger, NSString * _Nonnull);
/// Per-tick bitmap update for the speed-sign panel. Delivered on the
/// main thread after every GPS frame that produces new visuals.
/// Parameters:
/// <ul>
///   <li>
///     <code>currentImage</code>: the active speed-limit sign, or <code>nil</code> when the
///     matcher has no link under the GPS point.
///   </li>
///   <li>
///     <code>speedStatus</code>: <code>0</code> = within limit, <code>1</code> = approaching limit
///     (~80–100%), <code>2</code> = exceeding limit. Drive the colour of your
///     in-app speedometer from this.
///   </li>
///   <li>
///     <code>nextImage</code> / <code>nextDistMeters</code>: preview of the next sign ahead
///     plus distance in metres.
///   </li>
///   <li>
///     <code>cameraImage</code> / <code>cameraDistMeters</code>: preview of an upcoming
///     speed camera.
///   </li>
///   <li>
///     <code>tollImage</code> / <code>tollDistMeters</code>: preview of an upcoming toll booth.
///   </li>
///   <li>
///     <code>voiceWav</code>: optional 22050 Hz mono PCM WAV ready for
///     <code>AVAudioPlayer</code>. <code>nil</code> means nothing to announce this tick.
///   </li>
/// </ul>
/// <blockquote>
/// Important: Unlike Android, the iOS SDK has <em>no built-in voice
/// player</em>. The host app must always play <code>voiceWav</code> (and any
/// clips delivered via <code>onVoice</code>) itself — clips delivered while
/// no playback is wired will be silently dropped.
///
/// </blockquote>
@property (nonatomic, copy) void (^ _Nullable onBitmap)(UIImage * _Nullable, NSInteger, UIImage * _Nullable, NSInteger, UIImage * _Nullable, NSInteger, UIImage * _Nullable, NSInteger, NSData * _Nullable);
/// Voice clips for this GPS tick, each tagged with its trigger and
/// priority so the host can order/skip them. Parameters:
/// <code>(wav, trigger, priority)</code> where <code>priority</code> is
/// <code>0</code> = “hiện tại”/current (skip first when congested),
/// <code>1</code> = normal (approaching/camera/sign), <code>2</code> = speeding.
/// When this closure is set, <em>all</em> clips (including the first) are
/// delivered here and <code>onBitmap</code>’s <code>voiceWav</code> is <code>nil</code> — so there is no
/// double playback. When it is <code>nil</code>, the first clip falls back to
/// <code>onBitmap</code>’s <code>voiceWav</code> for legacy hosts.
/// <blockquote>
/// Important: The iOS SDK never plays voice automatically. If this
/// closure is <code>nil</code>, only the first clip (via <code>onBitmap</code>) is offered —
/// the host app is the only voice player.
///
/// </blockquote>
@property (nonatomic, copy) void (^ _Nullable onVoice)(NSData * _Nonnull, NSInteger, NSInteger);
/// Access restriction to display — đường cấm, cấm loại xe.
/// Restriction signs are split into three independent groups, because
/// they answer different questions and genuinely co-occur (a street
/// inside a built-up area can also ban stopping):
/// \code
/// access │ đường cấm, cấm loại xe │ may I drive here at all?
/// stop   │ cấm dừng, cấm đỗ       │ may I stop here?
/// bua    │ khu dân cư             │ what speed context is this?
///
/// \endcodeEach group has its own closure and deserves its own display slot; one
/// firing says nothing about the other two.
/// Delivered on the main thread. Parameters <code>(image, kind, distMeters)</code>:
/// <ul>
///   <li>
///     <code>image</code>: the sign, already decoded like the <code>onBitmap</code> signs.
///     <code>nil</code> when the slot must be hidden — either because <code>kind</code> is <code>0</code>,
///     or because that sign has no artwork embedded yet. Never treat <code>nil</code>
///     as an error.
///   </li>
///   <li>
///     <code>kind</code>: <code>MapZoneRestrictionSign</code> — 0 = none, 3 = đường cấm,
///     4 = cấm loại xe.
///   </li>
///   <li>
///     <code>distMeters</code>: <code>0</code> means “you are on it now” — hide the distance
///     label; <code>> 0</code> means the restriction starts that far ahead.
///   </li>
/// </ul>
/// Only fired when this group changes, not on every GPS tick: the same
/// <code>kind</code> moving less than 10 m is not re-emitted. When the restriction
/// ends, it fires exactly once with <code>kind = 0</code> and <code>image = nil</code>.
@property (nonatomic, copy) void (^ _Nullable onAccessRestriction)(UIImage * _Nullable, NSInteger, NSInteger);
/// Stop restriction to display — cấm dừng, cấm đỗ. See
/// <code>onAccessRestriction</code> for how the three groups relate and for the
/// parameter contract.
/// Only raised while the driver is actually slowing down or stopped.
/// <code>kind</code>: 0 = none, 1 = cấm đỗ, 2 = cấm dừng.
@property (nonatomic, copy) void (^ _Nullable onStopRestriction)(UIImage * _Nullable, NSInteger, NSInteger);
/// Built-up area sign to display — khu dân cư. See <code>onAccessRestriction</code>
/// for how the three groups relate and for the parameter contract.
/// Not a prohibition: it tells the driver which speed regime applies. The
/// artwork is a landscape rectangle, not a circle — size the slot
/// accordingly. <code>kind</code>: 0 = none, 5 = khu dân cư, 6 = hết khu dân cư.
@property (nonatomic, copy) void (^ _Nullable onBuildupArea)(UIImage * _Nullable, NSInteger, NSInteger);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Configure the base URL + auth credentials + vehicle profile.
/// Call once before the first <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code>.
/// The host bundle identifier is resolved automatically from
/// <code>Bundle.main</code> — the integrator does not pass it. It is used verbatim
/// as the auth bundle id, so it must be whitelisted for <code>apiKeyId</code>
/// exactly as configured in the app target.
/// note:
/// Throws an Objective-C exception with name
/// <code>"InvalidArgument"</code> if <code>baseUrl</code> does not start with <code>https://</code>.
/// important:
/// When the SDK is used from an app extension (widget,
/// CarPlay scene bundled separately, …), <code>Bundle.main</code> is the
/// <em>extension’s</em> bundle — not the host app’s — so the extension’s
/// bundle id must be whitelisted too, or the auth call fails with
/// error code <code>2003</code>.
/// \param baseUrl Bare host of the zone API, e.g.
/// <code>"https://driving.map.zone"</code>. Must start with <code>https://</code>.
///
/// \param apiKeyId Public API Key ID issued for this app.
///
/// \param apiKey Authentication secret paired with <code>apiKeyId</code>. Treat
/// it as a credential: do not log it, embed it in source
/// control, or expose it in user-facing UI.
///
/// \param vehicleId Vehicle identifier associated with <code>apiKeyId</code>.
///
/// \param vehicleType Vehicle category code (see SDK integration guide).
///
/// \param seats Number of seats — used to filter applicable alerts.
///
/// \param weights Vehicle gross weight in kg — used to filter applicable alerts.
///
- (void)configureWithBaseUrl:(NSString * _Nonnull)baseUrl apiKeyId:(NSString * _Nonnull)apiKeyId apiKey:(NSString * _Nonnull)apiKey vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(NSInteger)weights;
/// Notify the engine of a position change without motion context.
/// Equivalent to <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code> with
/// <code>speedKmh = 0</code> and <code>bearingDeg = .nan</code>. Most integrations should
/// prefer the four-argument overload so the engine can prefetch the
/// next zone earlier when driving fast and along the heading.
- (void)updateLocationWithLat:(double)lat lng:(double)lng;
/// Notify the engine of a position change with motion context.
/// Safe to call on the main thread — the actual zone work runs on a
/// background queue. Call this on every GPS update. The engine
/// internally throttles network requests, so calling at 1 Hz costs
/// nothing when the vehicle hasn’t moved far enough to warrant a
/// reload.
/// \param lat Latitude in degrees (WGS84).
///
/// \param lng Longitude in degrees (WGS84).
///
/// \param speedKmh Current GPS speed in km/h. Forwarded to the engine
/// so the prefetch margin scales with speed: faster driving
/// triggers the next zone fetch further ahead of the edge.
///
/// \param bearingDeg Heading in degrees (0 = N, 90 = E). The request
/// sent to the server is projected ~400m forward along this
/// bearing so an edge-of-zone GPS does not produce a
/// same-zone response. Pass <code>.nan</code> when bearing is unknown.
///
- (void)updateLocationWithLat:(double)lat lng:(double)lng speedKmh:(double)speedKmh bearingDeg:(double)bearingDeg;
/// Feed a GPS frame to the matching and alert pipeline.
/// This drives the per-tick UI: map-matching, current speed-sign
/// lookup, “next sign / camera / toll” preview, speeding detection,
/// and voice cue generation. Call once per GPS update, after
/// <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code>.
/// Runs on the same serial queue as <code>updateLocation</code>, so the engine
/// never sees a <code>processGps</code> call mid-way through a zone reload.
/// \param lat Latitude in degrees (WGS84).
///
/// \param lng Longitude in degrees (WGS84).
///
/// \param bearing Heading in degrees (0 = N, 90 = E).
///
/// \param speedKmh Current speed in km/h.
///
/// \param accuracy Horizontal accuracy radius in metres
/// (<code>CLLocation.horizontalAccuracy</code>).
///
/// \param timestampMs Epoch milliseconds of the fix itself —
/// <code>Int64(location.timestamp.timeIntervalSince1970 * 1000)</code>.
/// Pass the fix’s own time, never <code>Date()</code>: the engine measures voice
/// throttling and stop detection against this clock, and the delay
/// between CoreLocation producing the fix and this call reaching the
/// engine (queue hop + processing) is exactly what those intervals
/// must not absorb. Mirrors Android’s <code>Location.getTime()</code>.
///
- (void)processGpsWithLat:(double)lat lng:(double)lng bearing:(double)bearing speedKmh:(double)speedKmh accuracy:(double)accuracy timestampMs:(int64_t)timestampMs;
/// Clear all loaded zone data and reset internal state.
/// Call this when the vehicle profile changes (e.g. driver swaps
/// <code>vehicleType</code> / <code>seats</code> / <code>weights</code>) or when the user ends a
/// navigation session and you want to free the engine’s memory. The
/// next <code>updateLocation</code> call will trigger a fresh fetch.
- (void)reset;
/// Objective-C entry point for <code>setMutedAlertTypes(_:)</code>.
/// <code>Set<VoiceAlertType></code> is not representable in Objective-C, so ObjC
/// hosts pass the raw <code>VoiceAlertType</code> values boxed in <code>NSNumber</code>:
/// \code
/// [manager setMutedAlertTypeValues:@[@(VoiceAlertTypeSpeedCamera),
///                                    @(VoiceAlertTypeToll)]];
///
/// \endcodeSemantics are identical to <code>setMutedAlertTypes(_:)</code> — see it for the
/// mute rules. Values matching no <code>VoiceAlertType</code> case are ignored rather
/// than raising, so a host built against a newer enum degrades quietly.
/// \param rawValues categories to suppress; empty re-enables all.
///
- (void)setMutedAlertTypeValues:(NSArray<NSNumber *> * _Nonnull)rawValues;
/// Begin appending native logs to <code>path</code>. Pass <code>nil</code> to disable file
/// logging. Useful for field tests where the Xcode console is
/// unavailable; pair with <code>flushLog()</code> before sharing the file.
/// <blockquote>
/// Important: <em>Debug builds only.</em> The XCFramework published to
/// integrators is built in Release configuration, which compiles
/// every native log call site out of the binary — there is
/// nothing for the file sink to capture. In a release build this
/// method is a no-op that returns <code>false</code> without creating any
/// file, so callers can detect the disabled-in-production state
/// instead of finding an empty file on disk and assuming the SDK
/// is broken.
///
/// </blockquote>
///
/// returns:
/// <code>true</code> when the file was successfully opened for
/// appending. Always <code>false</code> on release builds.
- (BOOL)setLogFilePath:(NSString * _Nullable)path;
/// Current native log file path, or empty string when file logging
/// is off (including all release builds — see <code>setLogFilePath</code>).
@property (nonatomic, readonly, copy) NSString * _Nonnull logFilePath;
/// Flush pending bytes to disk before sharing the log file. No-op
/// on release builds (see <code>setLogFilePath</code>).
- (void)flushLog;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2 effective-5.10 (swiftlang-6.2.0.19.9 clang-1700.3.19.1)
#ifndef MAPZONESPEEDALERTSDK_SWIFT_H
#define MAPZONESPEEDALERTSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import _LocationEssentials;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="MapZoneSpeedAlertSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class CLLocation;
@class NSString;
SWIFT_CLASS("_TtC20MapZoneSpeedAlertSDK23EnhancedLocationManager")
@interface EnhancedLocationManager : NSObject
@property (nonatomic, copy) void (^ _Nullable onLocationUpdate)(CLLocation * _Nonnull, NSString * _Nonnull, NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onLocationError)(NSString * _Nonnull);
@property (nonatomic, copy) void (^ _Nullable onAuthorizationChanged)(CLAuthorizationStatus);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)startTrackingWithHighAccuracyMode:(BOOL)highAccuracyMode SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)stopTracking;
- (void)requestLocationPermissions SWIFT_AVAILABILITY(ios,introduced=14.0);
- (BOOL)isTracking SWIFT_WARN_UNUSED_RESULT;
- (CLLocation * _Nullable)getLastKnownLocation SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)getLocationServicesStatus SWIFT_WARN_UNUSED_RESULT SWIFT_AVAILABILITY(ios,introduced=14.0);
- (void)requestFullAccuracy;
- (void)setCustomAccuracy:(CLLocationAccuracy)accuracy distanceFilter:(CLLocationDistance)distanceFilter;
- (void)enableBackgroundLocationUpdates:(BOOL)enable SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

@class CLLocationManager;
@interface EnhancedLocationManager (SWIFT_EXTENSION(MapZoneSpeedAlertSDK)) <CLLocationManagerDelegate>
- (void)locationManager:(CLLocationManager * _Nonnull)manager didUpdateLocations:(NSArray<CLLocation *> * _Nonnull)locations;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didFailWithError:(NSError * _Nonnull)error;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
- (void)locationManagerDidChangeAuthorization:(CLLocationManager * _Nonnull)manager SWIFT_AVAILABILITY(ios,introduced=14.0);
@end

/// Vehicle type for MapZone Speed Alert SDK.
/// Values aligned with Zone Network v4 backend enum
/// (<code>drivingalert/api/v1/Zone/network?vehicleType=...</code>).
typedef SWIFT_ENUM(NSInteger, VehicleType, open) {
  VehicleTypeCar = 1,
  VehicleTypeMotorcycle = 2,
  VehicleTypeTruck = 3,
  VehicleTypeCoach = 4,
  VehicleTypeBus = 5,
  VehicleTypeTaxi = 6,
  VehicleTypeBicycle = 7,
  VehicleTypePedestrian = 8,
  VehicleTypeEmergency = 9,
};

/// Configurable voice-alert categories the host app can mute.
/// Each case maps 1:1 to a native <code>VoiceTrigger</code> (see <code>graph_engine_v2.hpp</code>).
/// Use with <code>ZoneNetworkManager/setMutedAlertTypes(_:)</code> to choose which
/// alert voices are spoken and which are skipped. From Objective-C, call
/// <code>ZoneNetworkManager/setMutedAlertTypeValues(_:)</code> instead and box these
/// values in <code>NSNumber</code> — a <code>Set</code> of enums cannot cross the ObjC bridge.
/// note:
/// Speed-limit (“hiện tại” / “tiếp theo”) and speeding warnings are
/// core safety cues and are always announced — they have no case here, and
/// their on-screen sign always shows.
/// Muting a camera or toll category also hides its on-screen icon together
/// with its voice. The other sign categories (no-turn, no-parking, …)
/// currently have no icon, so muting them only silences the voice.
typedef SWIFT_ENUM(NSInteger, VoiceAlertType, open) {
  VoiceAlertTypeSpeedCamera = 3,
  VoiceAlertTypeToll = 4,
  VoiceAlertTypeTrafficEnforcementCamera = 6,
  VoiceAlertTypeRedLightCamera = 7,
  VoiceAlertTypeAiCamera = 8,
  VoiceAlertTypeNoLeftTurn = 9,
  VoiceAlertTypeNoRightTurn = 10,
  VoiceAlertTypeNoUTurn = 11,
  VoiceAlertTypeNoOvertaking = 12,
  VoiceAlertTypeNoOvertakingEnd = 13,
  VoiceAlertTypeNoParking = 14,
  VoiceAlertTypeNoStraight = 15,
  VoiceAlertTypeBuildUpAreaStart = 16,
  VoiceAlertTypeBuildUpAreaEnd = 17,
  VoiceAlertTypeRestStation = 18,
  VoiceAlertTypeNoStopping = 19,
  VoiceAlertTypeRoadClosed = 20,
  VoiceAlertTypeVehicleRestricted = 21,
};

@class UIImage;
@class NSData;
@class NSNumber;
/// Entry point for the MapZone Speed Alert engine on iOS.
/// Holds the configuration for a single vehicle profile and forwards each
/// GPS update to the native engine. The engine performs zone loading,
/// map-matching, speed-sign bitmap rendering, and voice clip generation
/// on background queues; this class only schedules work and dispatches
/// results back to the main thread.
/// <h3>Usage</h3>
/// \code
/// // 1. Create, then configure with vehicle credentials and profile.
/// let manager = ZoneNetworkManager()
/// manager.configure(
///     baseUrl: "https://driving.map.zone",
///     apiKeyId: "<apiKeyId>", apiKey: "<apiKey>",
///     vehicleId: "<vehicleId>",
///     vehicleType: 1, seats: 1, weights: 1)
///
/// // 2. Subscribe to UI events.
/// manager.onReady   = { links, alerts in ... }
/// manager.onBitmap  = { current, status, next, nextDist,
///                       camera, camDist, toll, tollDist, voiceWav in ... }
/// manager.onResult = { success, code, message in ... }
/// manager.onAccessRestriction = { bmp, kind, distMeters in ... }
/// manager.onStopRestriction   = { bmp, kind, distMeters in ... }
/// manager.onBuildupArea       = { bmp, kind, distMeters in ... }
///
/// // 3. Feed every GPS frame.
/// manager.updateLocation(lat: lat, lng: lng,
///                        speedKmh: speedKmh, bearingDeg: bearing)
/// manager.processGps(lat: lat, lng: lng, bearing: bearing,
///                    speedKmh: speedKmh, accuracy: accuracy,
///                    timestampMs: Int64(location.timestamp
///                                         .timeIntervalSince1970 * 1000))
///
/// \endcodeAll public methods are safe to call from the main thread. Internally
/// the manager uses a single serial dispatch queue so calls are
/// serialised — concurrent <code>updateLocation</code> and <code>processGps</code> will not
/// race against each other.
SWIFT_CLASS("_TtC20MapZoneSpeedAlertSDK18ZoneNetworkManager")
@interface ZoneNetworkManager : NSObject
/// Fired on the main thread after each successful zone load.
/// Use it to enable UI that depends on having data — e.g. show the
/// speed-sign panel, or refresh a debug overlay with the new zone
/// bbox. Parameters are <code>(linkCount, alertCount)</code>.
@property (nonatomic, copy) void (^ _Nullable onReady)(NSInteger, NSInteger);
/// Fired on the main thread after every zone-reload attempt.
/// Useful for surfacing server-side errors to the user.
/// <ul>
///   <li>
///     <code>success</code>: <code>true</code> when fresh zone data was loaded.
///   </li>
///   <li>
///     <code>errorCode</code>: <code>0</code> on success. Positive values are server-reported
///     errors (e.g. <code>2003</code> unauthorized, <code>1001</code> invalid parameter,
///     <code>3003</code> vehicle type not supported). Negative values are local SDK
///     failures: <code>-1</code> response could not be verified, <code>-2</code> data invalid,
///     <code>-3</code> secure session failed, <code>-4</code> server unreachable, <code>-5</code> the
///     native bridge failed (rejected configuration, call threw).
///   </li>
///   <li>
///     <code>errorMessage</code>: a curated sentence derived from <code>errorCode</code> alone.
///     The server’s own wording never appears here — localise off the
///     numeric code if you need anything other than English.
///   </li>
/// </ul>
@property (nonatomic, copy) void (^ _Nullable onResult)(BOOL, NSInteger, NSString * _Nonnull);
/// Per-tick bitmap update for the speed-sign panel. Delivered on the
/// main thread after every GPS frame that produces new visuals.
/// Parameters:
/// <ul>
///   <li>
///     <code>currentImage</code>: the active speed-limit sign, or <code>nil</code> when the
///     matcher has no link under the GPS point.
///   </li>
///   <li>
///     <code>speedStatus</code>: <code>0</code> = within limit, <code>1</code> = approaching limit
///     (~80–100%), <code>2</code> = exceeding limit. Drive the colour of your
///     in-app speedometer from this.
///   </li>
///   <li>
///     <code>nextImage</code> / <code>nextDistMeters</code>: preview of the next sign ahead
///     plus distance in metres.
///   </li>
///   <li>
///     <code>cameraImage</code> / <code>cameraDistMeters</code>: preview of an upcoming
///     speed camera.
///   </li>
///   <li>
///     <code>tollImage</code> / <code>tollDistMeters</code>: preview of an upcoming toll booth.
///   </li>
///   <li>
///     <code>voiceWav</code>: optional 22050 Hz mono PCM WAV ready for
///     <code>AVAudioPlayer</code>. <code>nil</code> means nothing to announce this tick.
///   </li>
/// </ul>
/// <blockquote>
/// Important: Unlike Android, the iOS SDK has <em>no built-in voice
/// player</em>. The host app must always play <code>voiceWav</code> (and any
/// clips delivered via <code>onVoice</code>) itself — clips delivered while
/// no playback is wired will be silently dropped.
///
/// </blockquote>
@property (nonatomic, copy) void (^ _Nullable onBitmap)(UIImage * _Nullable, NSInteger, UIImage * _Nullable, NSInteger, UIImage * _Nullable, NSInteger, UIImage * _Nullable, NSInteger, NSData * _Nullable);
/// Voice clips for this GPS tick, each tagged with its trigger and
/// priority so the host can order/skip them. Parameters:
/// <code>(wav, trigger, priority)</code> where <code>priority</code> is
/// <code>0</code> = “hiện tại”/current (skip first when congested),
/// <code>1</code> = normal (approaching/camera/sign), <code>2</code> = speeding.
/// When this closure is set, <em>all</em> clips (including the first) are
/// delivered here and <code>onBitmap</code>’s <code>voiceWav</code> is <code>nil</code> — so there is no
/// double playback. When it is <code>nil</code>, the first clip falls back to
/// <code>onBitmap</code>’s <code>voiceWav</code> for legacy hosts.
/// <blockquote>
/// Important: The iOS SDK never plays voice automatically. If this
/// closure is <code>nil</code>, only the first clip (via <code>onBitmap</code>) is offered —
/// the host app is the only voice player.
///
/// </blockquote>
@property (nonatomic, copy) void (^ _Nullable onVoice)(NSData * _Nonnull, NSInteger, NSInteger);
/// Access restriction to display — đường cấm, cấm loại xe.
/// Restriction signs are split into three independent groups, because
/// they answer different questions and genuinely co-occur (a street
/// inside a built-up area can also ban stopping):
/// \code
/// access │ đường cấm, cấm loại xe │ may I drive here at all?
/// stop   │ cấm dừng, cấm đỗ       │ may I stop here?
/// bua    │ khu dân cư             │ what speed context is this?
///
/// \endcodeEach group has its own closure and deserves its own display slot; one
/// firing says nothing about the other two.
/// Delivered on the main thread. Parameters <code>(image, kind, distMeters)</code>:
/// <ul>
///   <li>
///     <code>image</code>: the sign, already decoded like the <code>onBitmap</code> signs.
///     <code>nil</code> when the slot must be hidden — either because <code>kind</code> is <code>0</code>,
///     or because that sign has no artwork embedded yet. Never treat <code>nil</code>
///     as an error.
///   </li>
///   <li>
///     <code>kind</code>: <code>MapZoneRestrictionSign</code> — 0 = none, 3 = đường cấm,
///     4 = cấm loại xe.
///   </li>
///   <li>
///     <code>distMeters</code>: <code>0</code> means “you are on it now” — hide the distance
///     label; <code>> 0</code> means the restriction starts that far ahead.
///   </li>
/// </ul>
/// Only fired when this group changes, not on every GPS tick: the same
/// <code>kind</code> moving less than 10 m is not re-emitted. When the restriction
/// ends, it fires exactly once with <code>kind = 0</code> and <code>image = nil</code>.
@property (nonatomic, copy) void (^ _Nullable onAccessRestriction)(UIImage * _Nullable, NSInteger, NSInteger);
/// Stop restriction to display — cấm dừng, cấm đỗ. See
/// <code>onAccessRestriction</code> for how the three groups relate and for the
/// parameter contract.
/// Only raised while the driver is actually slowing down or stopped.
/// <code>kind</code>: 0 = none, 1 = cấm đỗ, 2 = cấm dừng.
@property (nonatomic, copy) void (^ _Nullable onStopRestriction)(UIImage * _Nullable, NSInteger, NSInteger);
/// Built-up area sign to display — khu dân cư. See <code>onAccessRestriction</code>
/// for how the three groups relate and for the parameter contract.
/// Not a prohibition: it tells the driver which speed regime applies. The
/// artwork is a landscape rectangle, not a circle — size the slot
/// accordingly. <code>kind</code>: 0 = none, 5 = khu dân cư, 6 = hết khu dân cư.
@property (nonatomic, copy) void (^ _Nullable onBuildupArea)(UIImage * _Nullable, NSInteger, NSInteger);
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Configure the base URL + auth credentials + vehicle profile.
/// Call once before the first <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code>.
/// The host bundle identifier is resolved automatically from
/// <code>Bundle.main</code> — the integrator does not pass it. It is used verbatim
/// as the auth bundle id, so it must be whitelisted for <code>apiKeyId</code>
/// exactly as configured in the app target.
/// note:
/// Throws an Objective-C exception with name
/// <code>"InvalidArgument"</code> if <code>baseUrl</code> does not start with <code>https://</code>.
/// important:
/// When the SDK is used from an app extension (widget,
/// CarPlay scene bundled separately, …), <code>Bundle.main</code> is the
/// <em>extension’s</em> bundle — not the host app’s — so the extension’s
/// bundle id must be whitelisted too, or the auth call fails with
/// error code <code>2003</code>.
/// \param baseUrl Bare host of the zone API, e.g.
/// <code>"https://driving.map.zone"</code>. Must start with <code>https://</code>.
///
/// \param apiKeyId Public API Key ID issued for this app.
///
/// \param apiKey Authentication secret paired with <code>apiKeyId</code>. Treat
/// it as a credential: do not log it, embed it in source
/// control, or expose it in user-facing UI.
///
/// \param vehicleId Vehicle identifier associated with <code>apiKeyId</code>.
///
/// \param vehicleType Vehicle category code (see SDK integration guide).
///
/// \param seats Number of seats — used to filter applicable alerts.
///
/// \param weights Vehicle gross weight in kg — used to filter applicable alerts.
///
- (void)configureWithBaseUrl:(NSString * _Nonnull)baseUrl apiKeyId:(NSString * _Nonnull)apiKeyId apiKey:(NSString * _Nonnull)apiKey vehicleId:(NSString * _Nonnull)vehicleId vehicleType:(NSInteger)vehicleType seats:(NSInteger)seats weights:(NSInteger)weights;
/// Notify the engine of a position change without motion context.
/// Equivalent to <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code> with
/// <code>speedKmh = 0</code> and <code>bearingDeg = .nan</code>. Most integrations should
/// prefer the four-argument overload so the engine can prefetch the
/// next zone earlier when driving fast and along the heading.
- (void)updateLocationWithLat:(double)lat lng:(double)lng;
/// Notify the engine of a position change with motion context.
/// Safe to call on the main thread — the actual zone work runs on a
/// background queue. Call this on every GPS update. The engine
/// internally throttles network requests, so calling at 1 Hz costs
/// nothing when the vehicle hasn’t moved far enough to warrant a
/// reload.
/// \param lat Latitude in degrees (WGS84).
///
/// \param lng Longitude in degrees (WGS84).
///
/// \param speedKmh Current GPS speed in km/h. Forwarded to the engine
/// so the prefetch margin scales with speed: faster driving
/// triggers the next zone fetch further ahead of the edge.
///
/// \param bearingDeg Heading in degrees (0 = N, 90 = E). The request
/// sent to the server is projected ~400m forward along this
/// bearing so an edge-of-zone GPS does not produce a
/// same-zone response. Pass <code>.nan</code> when bearing is unknown.
///
- (void)updateLocationWithLat:(double)lat lng:(double)lng speedKmh:(double)speedKmh bearingDeg:(double)bearingDeg;
/// Feed a GPS frame to the matching and alert pipeline.
/// This drives the per-tick UI: map-matching, current speed-sign
/// lookup, “next sign / camera / toll” preview, speeding detection,
/// and voice cue generation. Call once per GPS update, after
/// <code>updateLocation(lat:lng:speedKmh:bearingDeg:)</code>.
/// Runs on the same serial queue as <code>updateLocation</code>, so the engine
/// never sees a <code>processGps</code> call mid-way through a zone reload.
/// \param lat Latitude in degrees (WGS84).
///
/// \param lng Longitude in degrees (WGS84).
///
/// \param bearing Heading in degrees (0 = N, 90 = E).
///
/// \param speedKmh Current speed in km/h.
///
/// \param accuracy Horizontal accuracy radius in metres
/// (<code>CLLocation.horizontalAccuracy</code>).
///
/// \param timestampMs Epoch milliseconds of the fix itself —
/// <code>Int64(location.timestamp.timeIntervalSince1970 * 1000)</code>.
/// Pass the fix’s own time, never <code>Date()</code>: the engine measures voice
/// throttling and stop detection against this clock, and the delay
/// between CoreLocation producing the fix and this call reaching the
/// engine (queue hop + processing) is exactly what those intervals
/// must not absorb. Mirrors Android’s <code>Location.getTime()</code>.
///
- (void)processGpsWithLat:(double)lat lng:(double)lng bearing:(double)bearing speedKmh:(double)speedKmh accuracy:(double)accuracy timestampMs:(int64_t)timestampMs;
/// Clear all loaded zone data and reset internal state.
/// Call this when the vehicle profile changes (e.g. driver swaps
/// <code>vehicleType</code> / <code>seats</code> / <code>weights</code>) or when the user ends a
/// navigation session and you want to free the engine’s memory. The
/// next <code>updateLocation</code> call will trigger a fresh fetch.
- (void)reset;
/// Objective-C entry point for <code>setMutedAlertTypes(_:)</code>.
/// <code>Set<VoiceAlertType></code> is not representable in Objective-C, so ObjC
/// hosts pass the raw <code>VoiceAlertType</code> values boxed in <code>NSNumber</code>:
/// \code
/// [manager setMutedAlertTypeValues:@[@(VoiceAlertTypeSpeedCamera),
///                                    @(VoiceAlertTypeToll)]];
///
/// \endcodeSemantics are identical to <code>setMutedAlertTypes(_:)</code> — see it for the
/// mute rules. Values matching no <code>VoiceAlertType</code> case are ignored rather
/// than raising, so a host built against a newer enum degrades quietly.
/// \param rawValues categories to suppress; empty re-enables all.
///
- (void)setMutedAlertTypeValues:(NSArray<NSNumber *> * _Nonnull)rawValues;
/// Begin appending native logs to <code>path</code>. Pass <code>nil</code> to disable file
/// logging. Useful for field tests where the Xcode console is
/// unavailable; pair with <code>flushLog()</code> before sharing the file.
/// <blockquote>
/// Important: <em>Debug builds only.</em> The XCFramework published to
/// integrators is built in Release configuration, which compiles
/// every native log call site out of the binary — there is
/// nothing for the file sink to capture. In a release build this
/// method is a no-op that returns <code>false</code> without creating any
/// file, so callers can detect the disabled-in-production state
/// instead of finding an empty file on disk and assuming the SDK
/// is broken.
///
/// </blockquote>
///
/// returns:
/// <code>true</code> when the file was successfully opened for
/// appending. Always <code>false</code> on release builds.
- (BOOL)setLogFilePath:(NSString * _Nullable)path;
/// Current native log file path, or empty string when file logging
/// is off (including all release builds — see <code>setLogFilePath</code>).
@property (nonatomic, readonly, copy) NSString * _Nonnull logFilePath;
/// Flush pending bytes to disk before sharing the log file. No-op
/// on release builds (see <code>setLogFilePath</code>).
- (void)flushLog;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
